import {NextResponse} from "next/server";
import {z} from "zod";
import {getCurrentUser} from "@/lib/auth/session";
import {connectDB} from "@/lib/db/mongoose";
import {BookingModel} from "@/models/Booking";
import {TripLocationModel} from "@/models/TripLocation";
const locationSchema=z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180),accuracy:z.number().optional(),heading:z.number().optional(),speed:z.number().optional()});
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user||user.role!=="driver")return NextResponse.json({error:"Driver authentication required"},{status:401});const {id}=await params;try{const data=locationSchema.parse(await req.json());await connectDB();const booking=await BookingModel.findOne({_id:id,driverId:user.id,status:{$in:["confirmed","driver_en_route","driver_arrived","trip_started","trip_paused"]}}).lean();if(!booking)return NextResponse.json({error:"Active booking not found"},{status:404});await TripLocationModel.create({bookingId:id,driverId:user.id,...data,recordedAt:new Date()});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Location update failed"},{status:400});}}
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Authentication required"},{status:401});const {id}=await params;await connectDB();const booking=await BookingModel.findById(id).lean();if(!booking)return NextResponse.json({error:"Booking not found"},{status:404});const allowed=user.role==="customer"?String(booking.customerId)===user.id:user.role==="driver"?String(booking.driverId)===user.id:["admin","operations","support"].includes(user.role);if(!allowed)return NextResponse.json({error:"Forbidden"},{status:403});const latest=await TripLocationModel.findOne({bookingId:id}).sort({recordedAt:-1}).lean();return NextResponse.json({location:latest??null,status:booking.status},{headers:{"Cache-Control":"no-store"}});}
